version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - chromagen-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://chromagen:password@db:5432/chromagen
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    networks:
      - chromagen-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=chromagen
      - POSTGRES_USER=chromagen
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - chromagen-network

volumes:
  postgres_data:

networks:
  chromagen-network:
    driver: bridge